import { confirmDelete } from '../../components/deleteConfirmation';
import { useState } from 'react';
import Paper from '@mui/material/Paper';
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, IconButton, TextField, TablePagination } from '@mui/material';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import PrintOutlinedIcon from '@mui/icons-material/PrintOutlined';
import { SeaLocalInvoice } from '../../domain/seaLocalInvoice';
type Props={invoices:SeaLocalInvoice[];onOpen:(i:SeaLocalInvoice)=>void;onEdit:(i:SeaLocalInvoice)=>void;onDelete:(i:SeaLocalInvoice)=>void;onPrint:(i:SeaLocalInvoice)=>void};
export function SeaLocalInvoiceGrid({invoices,onOpen,onEdit,onDelete,onPrint}:Props){const[f,setF]=useState<Record<number,string>>({});const[p,setP]=useState(0);const[n,setN]=useState(10);const vals=(i:SeaLocalInvoice)=>[i.invoiceNo,i.date,i.branch,i.jobNo,i.type,i.lclFcl,'','',i.pkgs,i.partyCode,i.partyName,i.consignee,i.subAgentParty,i.portOfLoad,i.destination,i.mblNo||i.hblNo,i.invoiceTotalPkr,i.status.final?'Y':'N',i.status.posted?'Y':'N',i.status.void?'Y':'N'].map(String);const rows=invoices.filter(i=>vals(i).every((v,x)=>v.toLowerCase().includes((f[x]||'').toLowerCase())));const q=rows.slice(p*n,p*n+n);const h=['No.','Date','Branch','Job No.','Job Type','LCL/FCL','Vessel','ETD','Pkgs','Code','Name','Consignee','Sub-Agent Party','Origin','Destination','MBL/HBL No.','Invoice Amount','Final','Post','Void'];return <TableContainer component={Paper} variant="outlined"><Table size="small" sx={{minWidth:1900}}><TableHead><TableRow><TableCell rowSpan={2} sx={{fontWeight:700}}>Action</TableCell><TableCell colSpan={3} align="center" sx={{fontWeight:700}}>INVOICE</TableCell>{h.slice(3,8).map(x=><TableCell rowSpan={2} key={x}>{x}</TableCell>)}<TableCell colSpan={2} align="center">PARTY</TableCell>{h.slice(10).map(x=><TableCell rowSpan={2} key={x}>{x}</TableCell>)}</TableRow><TableRow>{h.slice(0,3).map(x=><TableCell key={x}>{x}</TableCell>)}<TableCell>Code</TableCell><TableCell>Name</TableCell></TableRow><TableRow><TableCell/>{h.map((x,i)=><TableCell key={x}><TextField size="small" type={x==='Date'||x==='ETD'?'date':'text'} value={f[i]||''} onChange={e=>{setF({...f,[i]:e.target.value});setP(0)}} sx={{minWidth:70}}/></TableCell>)}</TableRow></TableHead><TableBody>{q.map(i=><TableRow key={i.id}><TableCell><IconButton onClick={()=>onOpen(i)}><VisibilityOutlinedIcon/></IconButton><IconButton onClick={()=>onEdit(i)}><EditOutlinedIcon/></IconButton><IconButton onClick={()=>confirmDelete(() => onDelete(i))}><DeleteOutlineIcon/></IconButton><IconButton onClick={()=>onPrint(i)}><PrintOutlinedIcon/></IconButton></TableCell>{vals(i).map((v,x)=><TableCell key={x}>{v||'—'}</TableCell>)}</TableRow>)}</TableBody></Table><TablePagination component="div" count={rows.length} page={p} rowsPerPage={n} onPageChange={(_,x)=>setP(x)} onRowsPerPageChange={e=>{setN(+e.target.value);setP(0)}} rowsPerPageOptions={[5,10,25,50]}/></TableContainer>}
