import { v4 as uuid } from 'uuid';
import { AirImportJob } from './airImportJob';

const nowIso = () => new Date().toISOString();

export function createEmptyAirImportJob(branch = 'KHI'): AirImportJob {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    jobNo: '',
    jobDate: new Date().toISOString().slice(0, 10),
    finalDate: '',
    jobType: '',
    nomination: 'N',
    commodity: '',
    quotRefNo: '',
    doIssueDate: '',
    mawbNo: '',
    mawbDate: '',
    mawbPpCc: 'PP',
    mawbPcs: 0,
    mawbUom: '',
    mawbCbm: 0,
    mawbGrossWeight: 0,
    mawbChargeWeight: 0,
    hawbNo: '',
    hawbDate: '',
    hawbPpCc: 'PP',
    hawbPcs: 0,
    hawbUom: '',
    hawbCbm: 0,
    hawbGrossWeight: 0,
    hawbChargeWeight: 0,
    creditLimit: 0,
    partyCode: '',
    partyName: '',
    subAgentParty: '',
    foreignAgent: '',
    spoCode: '',
    origin: '',
    destination: '',
    flightNo: '',
    flightDate: '',
    custRefNo: '',
    clearingAgent: '',
    operationOfficer: '',
    airlineDoNo: '',
    airlineDoDate: '',
    beNo: '',
    beDate: '',
    igmNo: '',
    igmDate: '',
    indexNo: '',
    subIndexNo: '',
    etd: '',
    eta: '',
    lcNo: '',
    passportNo: '',
    docRcvDate: '',
    originDoNo: '',
    currency: '',
    vehicleNo: '',
    transporter: '',
    driver: '',
    driverCell: '',
    hsCode: '',
    roNo: '',
    houseAirwayBills: [],
    foreignAgentShipperNameAddress: '',
    notifyNameAddress: '',
    remarks: '',
    consigneeNameAddress: '',
    jobStatus: '',
    jobStatusDate: '',
    jobStatusRemarks: '',
    shippingTerm: 'FOB',
    intlInvoice: 'N',
    localInvoice: 'N',
    status: { final: false, void: false, posted: false, closed: false },
  };
}
