import { v4 as uuid } from 'uuid';
import { AirImportLocalInvoice } from './airImportLocalInvoice';
import { emptyStatus } from './common';

const nowIso = () => new Date().toISOString();

export function createEmptyAirImportLocalInvoice(branch = 'KHI'): AirImportLocalInvoice {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    invoiceNo: '',
    date: new Date().toISOString().slice(0, 10),
    jobNo: '',
    jobYear: new Date().getFullYear(),
    jobType: '',
    mawbNo: '',
    mawbDate: '',
    mawbPpCc: '',
    mawbPcs: 0,
    mawbCbm: 0,
    mawbGrossWeight: 0,
    mawbChargeWeight: 0,
    hawbNo: '',
    hawbDate: '',
    hawbPpCc: '',
    hawbPcs: 0,
    hawbCbm: 0,
    hawbGrossWeight: 0,
    hawbChargeWeight: 0,
    quotRefNo: '',
    partyCode: '',
    partyName: '',
    partyAddress: '',
    subAgentParty: '',
    spoCode: '',
    foreignAgent: '',
    commodity: '',
    origin: '',
    destination: '',
    postInPkr: 'Y',
    currencies: [
      { currencyCode: '', exRate: 0 },
      { currencyCode: '', exRate: 0 },
      { currencyCode: '', exRate: 0 },
    ],
    remarks: '',
    bankCode: '',
    bankDetailText: '',
    salesTaxPercent: 0,
    salesTaxInvoiceNo: '',
    whtSalesTaxPercent: 0,
    chargeLines: [
      { id: uuid(), description: 'Freight', cbmWtBasis: 'WT', curr: '', rate: 0, fAmount: 0, editableDescription: false },
      { id: uuid(), description: 'D/O Charges', cbmWtBasis: 'WT', curr: '', rate: 0, fAmount: 0, editableDescription: false },
    ],
    invoiceTotal: 0,
    refund: 0,
    refundExRate: 0,
    refund2: 0,
    refund3: 0,
    totalRefundAmount: 0,
    invoiceTotalPkr: 0,
    printRefundOnInvoice: 'Y',
    receipts: [],
    status: emptyStatus(),
  };
}
