import { v4 as uuid } from 'uuid';
import { emptyStatus } from './common';
import { emptyDueAgentLines, emptyDueCarrierLines } from './jobFactory';
import { InvoicePrintingOptions, JobRefPanel, LocalInvoice } from './localInvoice';

const nowIso = () => new Date().toISOString();

function emptyJobRefPanel(): JobRefPanel {
  return { jobNo: '', jobDate: '', awbNo: '', awbDate: '', pp: '', refNo: '' };
}

function emptyPrintingOptions(): InvoicePrintingOptions {
  return {
    documentType: 'INVOICE',
    printHeadingAs: 'INVOICE',
    startingInvoiceNo: '',
    endingInvoiceNo: '',
    printOn: 'LETTER_PAD',
    printIn: 'PKR',
    printCopyType: 'ORIGINAL',
    printQuotationNo: 'N',
    printDueDate: 'Y',
    printConsignee: 'Y',
    printSpoCodeName: 'N',
    printExRate: 'Y',
    printReceivedBy: 'N',
    printSignatorys: 'N',
    printNtnNo: 'Y',
  };
}

export function createEmptyLocalInvoice(branch = 'KHI'): LocalInvoice {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    invoiceNo: '',
    invoiceDate: new Date().toISOString().slice(0, 10),
    jobYear: new Date().getFullYear(),
    jobType: '',
    ccPort: '',
    house: emptyJobRefPanel(),
    master: emptyJobRefPanel(),
    ownerCode: '',
    partyCode: '',
    partyName: '',
    partyAddress: '',
    agentParty: '',
    airportOfDeparture: '',
    destination: '',
    spoCode: '',
    formENo: '',
    formEDate: '',
    sbNo: '',
    sbDate: '',
    shipperInvoiceNo: '',
    shipperInvoiceDate: '',
    postInPkr: 'N',
    currency1: 'USD',
    exRate1: 0,
    currency2: '',
    exRate2: 0,
    currency3: '',
    exRate3: 0,
    consignee: '',
    printableRemarks: '',
    nonPrintableRemarks: '',
    bankCode: '',
    bankDetailText: '',
    salesTaxPercent: 0,
    pstAmount: 0,
    praTax: 0,
    whtSalesTaxPercent: 0,
    whtSalesTaxAmount: 0,
    salesTaxInvoiceNo: '',
    praSrbTaxInvoiceNo: '',
    totalFreight: 0,
    totalDueCarrier: 0,
    totalDueAgent: 0,
    grossInvoiceAmount: 0,
    commissionPercent: 0,
    commissionAmount: 0,
    whtPercent: 0,
    whtAmount: 0,
    netRate: 'N',
    agreedRate: 0,
    agreedFreight: 0,
    freightDifference: 0,
    lessCommission: 0,
    kbRatePercent: 0,
    kbAmount: 0,
    totalDiscount: 0,
    invoiceTotal: 0,
    printIncentiveCommissionWht: 'N',
    receipts: [],
    dueCarrierLines: emptyDueCarrierLines(),
    totalDueCarrierComputed: 0,
    dueAgentLines: emptyDueAgentLines(),
    totalDueAgentComputed: 0,
    invoiceLines: [],
    airwayBillLines: [],
    awbCommissionAmount: 0,
    awbPayableToAirline: 0,
    awbExchangeRate: 0,
    printing: emptyPrintingOptions(),
    status: emptyStatus(),
  };
}
