import { v4 as uuid } from 'uuid';
import { emptyStatus } from './common';
import { SeaExportJob, TransshipmentPoint } from './seaExportJob';

const nowIso = () => new Date().toISOString();

function emptyTransshipmentPoints(): TransshipmentPoint[] {
  return Array.from({ length: 4 }, () => ({ id: uuid(), destinationCode: '', eta: '', etd: '', vessel: '', voyage: '' }));
}

export function createEmptySeaExportJob(branch = 'KHI'): SeaExportJob {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    jobNo: '',
    date: new Date().toISOString().slice(0, 10),
    jobType: '',
    loadProgramNo: '',
    consolNo: '',
    consolYN: 'N',
    nomination: 'N',
    partyCode: '',
    partyName: '',
    subAgentParty: '',
    commodity: '',
    foreignAgent: '',
    shippingLine: '',
    sLineAgent: '',
    deliveryAgent: '',
    spoCode: '',
    portOfLoad: '',
    destination: '',
    wharf: '',
    terminal: '',
    clearingAgent: '',
    jobStatus: '',
    jobStatusDate: '',
    bookingNo: '',
    consolTotal: { cbm: 0, grossWeight: 0, netWeight: 0, noOfPackages: 0, uom: '', noOfShipments: 0 },
    lastConsolNo: '',
    lclFcl: 'LCL',
    mPpCc: 'PP',
    cyCfs: 'CFS',
    hPpCc: 'PP',
    cyCfsCutOff: '',
    roNo: '',
    noOfPackages: 0,
    unit: '',
    noOfPcsQty: 0,
    unitQty: '',
    currencyCode: 'USD',
    exchangeRate: 0,
    grossWeight: 0,
    netWeight: 0,
    volWeight: 0,
    cbm: 0,
    cbmRate: 0,
    incoTerm: '',
    hsCode: '',
    stackCode: '',
    runNo: '',
    shipperInvoice: { invNo: '', date: '', currencyCode: 'USD', amount: 0, poNo: '' },
    ccDate: '',
    formEDate: '',
    formEInsNo2: '',
    formEInsNo2Date: '',
    formEInsNo3: '',
    formEInsNo3Date: '',
    shipReceivedDate: '',
    cuttOffDate: '',
    siFileCuttOff: '',
    handOverToSl: '',
    handOverToSlTime: '',
    docReceived: '',
    siFiled: '',
    docDespatchDate: '',
    sbNo: '',
    sbPlace: '',
    sbDate: '',
    mrNo: '',
    mrDate: '',
    egm: '',
    mblNo: '',
    mblDate: '',
    mblReceived: 'N',
    hblType: '',
    hblNo: '',
    hblDate: '',
    sailingDate: '',
    pickupStuffing: '',
    containers: [],
    invoiceRequired: 'N',
    localInvoice: 'N',
    intlInvoice: 'N',
    payableToSl: 'N',
    refundFromSl: 'N',
    ddShip: 'N',
    shipmentDelivered: 'N',
    deliveredDate: '',
    releaseMessageDate: '',
    preAlertDate: '',
    shipmentContainerized: 'N',
    nonPrintableRemarks: '',
    consolGrid: [],
    jobHistory: [],
    polEta: '',
    polEtaTime: '',
    polEtd: '',
    polEtdTime: '',
    etaAtDest: '',
    etaAtDestTime: '',
    vessel: '',
    voyage: '',
    rotationNo: '',
    transshipmentPoints: emptyTransshipmentPoints(),
    creditNoteDetails: [],
    bl: {
      hblType: '',
      mblNo: '',
      hblNo: '',
      docRefNo: '',
      partyCode: '',
      agentParty: '',
      address: '',
      consignee: '',
      notify: '',
      alsoNotify: '',
      deliveryAgent: '',
      formENo: '',
      formEDate: '',
      vessel: '',
      voyage: '',
      placeOfReceipt: '',
      placeOfLoading: '',
      placeOfDischarge: '',
      placeOfDelivery: '',
      freightPayableAt: '',
      noOfOrigBLs: 0,
      countryOfOrigin: '',
      placeOfIssue: '',
      hblDate: '',
      fobCif: 'FOB',
      cbm: 0,
      grossWeight: 0,
      volWeight: 0,
      netWeight: 0,
      bookingNo: '',
      loadingPier: '',
      reference: '',
      blReleasedAt: '',
      mop: '',
      freightChargesText: '',
      rate: 0,
      prepaid: 0,
      collect: 0,
      marksAndNos: '',
      descriptionOfGoods: '',
      sheet: '',
    },
    jobCharges: {
      currencies: [
        { curr: 'USD', exRate: 0 },
        { curr: '', exRate: 0 },
        { curr: '', exRate: 0 },
      ],
      lines: [],
      totalSellCharges: 0,
      totalBuyCharges: 0,
      totalGpAmount: 0,
      totalGpLessKb: 0,
    },
    consol: {
      consolNo: '',
      lclFcl: 'LCL',
      foreignAgent: '',
      shippingLine: '',
      sLineAgent: '',
      portOfLoad: '',
      portOfDischarge: '',
      wharf: '',
      terminal: '',
      mblNo: '',
      mblDate: '',
      vessel: '',
      voyage: '',
      rotationNo: '',
      containerNo: '',
      size: '',
      containerTypes: '',
      sealNo: '',
      pickupStuffing: '',
      cutOffDate: '',
      sailingDate: '',
      polEta: '',
      polEtd: '',
      etaAtDest: '',
    },
    instructionLetter: {
      mblNo: '',
      hblNo: '',
      docRefNo: '',
      partyCode: '',
      agentParty: '',
      address: '',
      consignee: '',
      notify: '',
      alsoNotify: '',
      deliveryAgent: '',
      formENo: '',
      formEDate: '',
      vessel: '',
      voyage: '',
      placeOfReceipt: '',
      placeOfLoading: '',
      placeOfDischarge: '',
      placeOfDelivery: '',
      freightPayableAt: '',
      noOfOrigBLs: 0,
      cbm: 0,
      grossWeight: 0,
      volWeight: 0,
      netWeight: 0,
      bookingNo: '',
      reference: '',
      mop: '',
      marksAndNos: '',
      descriptionOfGoods: '',
      sheet: '',
    },
    printing: {
      documentType: 'SHIPMENT_STATUS_REPORT',
      printOn: 'PLAIN_PAPER',
      todaysDate: new Date().toISOString().slice(0, 10),
      attention: '',
      note: '',
    },
    status: { ...emptyStatus(), closed: false },
  };
}

export function createEmptyContainer(id = uuid()) {
  return {
    id,
    containerNo: '',
    sizeType: '',
    sealNo: '',
    isoCode: '',
    vehicleNo: '',
    vehicleDate: '',
    vehicleEta: '',
    vehicleAta: '',
    serialNo: 0,
    containerTypes: '',
    vehicleType: '',
    polEta: '',
    polAta: '',
    pcd: '',
    transporterName: '',
    driverName: '',
    mobileNo: '',
    charges: 0,
    fromPol: '',
    toPod: '',
    noOfPkgs: 0,
    unit: '',
    cbm: 0,
    grossWeight: 0,
    netWeight: 0,
  };
}
