import { v4 as uuid } from 'uuid';
import { emptyStatus } from './common';
import { SeaForeignAgentInvoice, SeaForeignAgentInvoiceVariant } from './seaForeignAgentInvoice';

const nowIso = () => new Date().toISOString();

export function createEmptySeaForeignAgentInvoice(variant: SeaForeignAgentInvoiceVariant, branch = 'KHI'): SeaForeignAgentInvoice {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    variant,
    branch,
    documentNo: '',
    documentDate: new Date().toISOString().slice(0, 10),
    jobNo: '',
    jobYear: new Date().getFullYear(),
    consolNo: '',
    fAgentDocNo: '',
    dueDate: '',
    mblNo: '',
    mblDate: '',
    runNo: '',
    mPpCc: 'PP',
    hPpCc: 'PP',
    fAgentCode: '',
    fAgentName: '',
    origin: '',
    destination: '',
    pieces: 0,
    uom: '',
    lclFcl: 'LCL',
    grossWeight: 0,
    netWeight: 0,
    cbm: 0,
    vessel: '',
    voyage: '',
    carrier: '',
    remarks: '',
    postInPkr: 'N',
    currencyCode: 'USD',
    exchangeRate: 0,
    reference: '',
    consignee: '',
    bankCode: '',
    bankDetailText: '',
    receipts: [],
    containers: [],
    chargeLines: [],
    totalSelling: 0,
    totalBuying: 0,
    difference: 0,
    profitSharePercent: 0,
    lessExpenseLines: [],
    totalLessExpenses: 0,
    handlingLines: [],
    totalOtherCharges: 0,
    totalInvoiceAmount: 0,
    autoCalculateCost: 'N',
    autoCalcCostLines: [],
    autoCalcLines: [],
    printing: {
      printOn: 'PLAIN_PAPER',
      printIn: 'FOREIGN',
      printHeadingAs: 'INVOICE',
      printSignatorys: 'N',
      printCopyType: 'ORIGINAL',
    },
    status: emptyStatus(),
  };
}
