import { v4 as uuid } from 'uuid';
import { SeaImportQuotation } from './seaImportQuotation';

const nowIso = () => new Date().toISOString();

export function createEmptySeaImportQuotation(branch = 'KHI'): SeaImportQuotation {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    transportMode: '',
    date: new Date().toISOString().slice(0, 10),
    validity: '',
    quotationNo: '',
    callType: 'General',
    callTypeRef: '',
    supplQuoteNo: '',
    relatedQuoteNo: '',
    localIntl: 'Local',
    customerCode: '',
    partyCode: '',
    name: '',
    address: '',
    foreignAgentCode: '',
    spoCode: '',
    origin: '',
    destination: '',
    commodity: '',
    ccPort: '',
    ccDate: '',
    customerRefNo: '',
    pickUpLocation: '',
    dropOffLocation: '',
    noOfPkgs: 0,
    uom: '',
    packageType: '',
    grossWeight: 0,
    chWeight: 0,
    incoTerm: '',
    cargoType: 'General',
    cargoValue: 0,
    cargoCurr: '',
    cbm: 0,
    chargeCode: '',
    allIn: 'N',
    win: 'N',
    reason: '',
    hsCode: '',
    preparedBy: '',
    approvedBy: '',
    approvedByDate: '',
    closingReason: '',
    closingReasonDate: '',
    remarks: '',
    currencies: [
      { currencyCode: '', exRate: 0 },
      { currencyCode: '', exRate: 0 },
      { currencyCode: '', exRate: 0 },
    ],
    jobInfo: [],
    airlineRates: [],
    localCharges: [],
    carrierOptions: [],
    vendorInfo: null,
    termsAndConditions: '',
    extraSheet: '',
    serviceChargesOrigin: [],
    serviceChargesDestination: [],
    grandTotalBuying: 0,
    grandTotalSelling: 0,
    difference: 0,
    refundLines: [{ curr: '', amountFcr: 0, amount: 0, id: uuid() }],
    dimensions: Array.from({ length: 10 }, () => ({ length: 0, width: 0, height: 0, noOfCtns: 0, total: 0 })),
    dimWeight: 0,
    dimWeightDivisor: 0,
    dimCbm: 0,
    dimCbmDivisor: 0,
    status: { final: false },
  };
}
