import { v4 as uuid } from 'uuid';
import { SeaImportJob } from './seaImportJob';

const nowIso = () => new Date().toISOString();

export function createEmptySeaImportJob(branch = 'KHI'): SeaImportJob {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    jobNo: '',
    jobDate: new Date().toISOString().slice(0, 10),
    finalDate: '',
    jobType: '',
    nomination: 'N',
    commodity: '',
    consoleJob: '',
    quotRefNo: '',
    doIssueDate: '',
    mblNo: '',
    mblDate: '',
    mblPpCc: 'PP',
    mblPcs: 0,
    mblUom: '',
    mblCbm: 0,
    mblGrossWeight: 0,
    mblNetWeight: 0,
    hblNo: '',
    hblDate: '',
    hblPpCc: 'PP',
    hblPcs: 0,
    hblUom: '',
    hblCbm: 0,
    hblGrossWeight: 0,
    hblNetWeight: 0,
    creditLimit: 0,
    partyCode: '',
    partyName: '',
    subAgentParty: '',
    foreignAgent: '',
    shippingLine: '',
    sLineAgent: '',
    spoCode: '',
    origin: '',
    destination: '',
    portOfLoading: '',
    portOfDischarge: '',
    portOfShipment: '',
    viaPort: '',
    shed: '',
    terminal: '',
    clearingAgent: '',
    operationOfficer: '',
    stevedoring: '',
    marksAndNos: '',
    vessel: '',
    voyage: '',
    rotationNo: '',
    stackCode: '',
    eta: '',
    etd: '',
    beNo: '',
    beDate: '',
    indexNo: '',
    subIndexNo: '',
    igmNo: '',
    igmDate: '',
    lclFcl: 'LCL',
    arrivedDate: '',
    docRcvDate: '',
    nocValidDate: '',
    transporter: '',
    guarantee: '',
    vehicleNo: '',
    driver: '',
    driverCell: '',
    cyCfs: 'CFS/CFS',
    virNumber: '',
    custRefNo: '',
    hsCode: '',
    berthNo: '',
    freeDays: 0,
    totalDetentionDays: 0,
    currency: '',
    exRate: 0,
    detentionRatePerDay: 0,
    totalDetentionAmount: 0,
    roNo: '',
    hblLines: [],
    documentsList: [],
    foreignAgentShipperNameAddress: '',
    consigneeNameAddress: '',
    ntnNo: '',
    passportNo: '',
    cnicNo: '',
    notifyNameAddress: '',
    totalSecurityReceivable: 0,
    containerSecurityLines: [],
    balanceSecurityReceivable: 0,
    containers: [],
    consoleJobContainers: [],
    jobStatus: '',
    jobStatusDate: '',
    jobStatusRemarks: '',
    shippingTerm: 'FOB',
    intlInvoice: 'N',
    localInvoice: 'N',
    status: { final: false, void: false, posted: false, closed: false },
  };
}
