import { v4 as uuid } from 'uuid';
import { SeaImportLocalInvoice } from './seaImportLocalInvoice';
import { emptyStatus } from './common';

const nowIso = () => new Date().toISOString();

export function createEmptySeaImportLocalInvoice(branch = 'KHI'): SeaImportLocalInvoice {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    invoiceNo: '',
    date: new Date().toISOString().slice(0, 10),
    jobNo: '',
    jobYear: new Date().getFullYear(),
    jobType: '',
    mblNo: '',
    mblDate: '',
    mblPpCc: '',
    mblPcs: 0,
    mblCbm: 0,
    mblGrossWeight: 0,
    mblNetWeight: 0,
    hblNo: '',
    hblDate: '',
    hblPpCc: '',
    hblPcs: 0,
    hblCbm: 0,
    hblGrossWeight: 0,
    hblNetWeight: 0,
    quotRefNo: '',
    partyCode: '',
    partyName: '',
    partyAddress: '',
    subAgentParty: '',
    spoCode: '',
    foreignAgent: '',
    commodity: '',
    origin: '',
    destination: '',
    postInPkr: 'Y',
    currencies: [
      { currencyCode: '', exRate: 0 },
      { currencyCode: '', exRate: 0 },
      { currencyCode: '', exRate: 0 },
    ],
    remarks: '',
    bankCode: '',
    bankDetailText: '',
    salesTaxPercent: 0,
    salesTaxInvoiceNo: '',
    whtSalesTaxPercent: 0,
    chargeLines: [
      { id: uuid(), description: 'Freight', cbmWtBasis: 'WT', curr: '', qty: 0, rate: 0, fAmount: 0, editableDescription: false },
      { id: uuid(), description: 'Endorsement Fee', cbmWtBasis: 'WT', curr: '', qty: 0, rate: 0, fAmount: 0, editableDescription: false },
    ],
    invoiceTotal: 0,
    containers: [],
    refund: 0,
    refundExRate: 0,
    refund2: 0,
    refund3: 0,
    totalRefundAmount: 0,
    invoiceTotalPkr: 0,
    printRefundOnInvoice: 'Y',
    receipts: [],
    status: emptyStatus(),
  };
}
