import { v4 as uuid } from 'uuid';
import { SeaLocalInvoice } from './seaLocalInvoice';
import { emptyStatus } from './common';

const nowIso = () => new Date().toISOString();

export function createEmptySeaLocalInvoice(branch = 'KHI'): SeaLocalInvoice {
  return {
    id: uuid(),
    createdAt: nowIso(),
    updatedAt: nowIso(),
    branch,
    invoiceNo: '',
    date: new Date().toISOString().slice(0, 10),
    jobNo: '',
    jobYear: new Date().getFullYear(),
    type: '',
    quotRefNo: '',
    partyCode: '',
    partyName: '',
    partyAddress: '',
    subAgentParty: '',
    mblNo: '',
    hblNo: '',
    shipperInvoiceNo: '',
    shipperInvoiceDate: '',
    portOfLoad: '',
    destination: '',
    lclFcl: 'LCL',
    spoCode: '',
    consignee: '',
    remarks: '',
    cbm: 0,
    cbmRate: 0,
    fobCif: 'FOB',
    bankCode: '',
    bankDetailText: '',
    pkgs: 0,
    weightGrs: 0,
    weightNet: 0,
    weightVol: 0,
    postInPkr: 'Y',
    currency1: 'USD',
    exRate1: 0,
    currency2: '',
    exRate2: 0,
    currency3: '',
    exRate3: 0,
    containers: [],
    freight1: 0,
    freight2: 0,
    salesTaxPercent: 0,
    pstAmount: 0,
    whtSalesTaxPercent: 0,
    whtSalesTaxAmount: 0,
    praCode: 'PRA',
    praCharges: 0,
    salesTaxInvoiceNo: '',
    praSrbTaxInvoiceNo: '',
    slCharges: 0,
    otherCharges: 0,
    grossTotal: 0,
    refundCbmRate: 0,
    refund1: 0,
    refundExRate: 0,
    refund2: 0,
    refund3: 0,
    totalRefund: 0,
    invoiceTotal: 0,
    printRefundOnInvoice: 'N',
    shippingLineChargeLines: [
      {
        id: uuid(),
        code: 'SEA_FREIGHT',
        description: 'Sea Freight',
        cbmWtBasis: 'CBM',
        curr: 'USD',
        qty: 0,
        rate: 0,
        fAmount: 0,
        pkrAmount: 0,
      },
    ],
    totalSLineCharges: 0,
    otherChargeLines: [],
    totalOtherCharges: 0,
    invoiceTotalPkr: 0,
    documents: [],
    receipts: [],
    status: emptyStatus(),
  };
}
