import React, { useState } from 'react';
import Box from '@mui/material/Box'; import Button from '@mui/material/Button'; import MenuItem from '@mui/material/MenuItem'; import Paper from '@mui/material/Paper'; import Radio from '@mui/material/Radio'; import RadioGroup from '@mui/material/RadioGroup'; import FormControlLabel from '@mui/material/FormControlLabel'; import TextField from '@mui/material/TextField'; import Typography from '@mui/material/Typography'; import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf'; import TableViewIcon from '@mui/icons-material/TableView';
import { SeaImportLocalInvoice } from '../../domain/seaImportLocalInvoice';

const yn = (value: string, onChange: (value: string) => void) => <RadioGroup value={value} onChange={(e) => onChange(e.target.value)}><FormControlLabel value="Y" control={<Radio size="small"/>} label="Yes" sx={{height:23,m:0,fontWeight:700}}/><FormControlLabel value="N" control={<Radio size="small"/>} label="No" sx={{height:23,m:0,fontWeight:700}}/></RadioGroup>;
export function PrintingTab({ invoice }: { invoice: SeaImportLocalInvoice }) {
  const [print, setPrint] = useState('INVOICE'); const [printIn,setPrintIn]=useState('PKR'); const [paper,setPaper]=useState('PLAIN'); const [options,setOptions]=useState<Record<string,string>>({foreignTotals:'N',mblHbl:'Y',quotation:'N',dueDate:'N',consignee:'N',spo:'N',party:'Y',rate:'Y',received:'N',signatory:'N',ntn:'Y'});
  const option=(key:string)=>yn(options[key],v=>setOptions(o=>({...o,[key]:v})));
  const rows:[string,React.ReactNode][]=[['Branch',<TextField select size="small" value={invoice.branch} sx={{width:90}}><MenuItem value={invoice.branch}>{invoice.branch}</MenuItem></TextField>],['Print',<RadioGroup value={print} onChange={e=>setPrint(e.target.value)}><FormControlLabel value="INVOICE" control={<Radio size="small"/>} label="Invoice" sx={{height:23,m:0,fontWeight:700}}/><FormControlLabel value="SALES_TAX" control={<Radio size="small"/>} label="Sales Tax Invoice" sx={{height:23,m:0,fontWeight:700}}/></RadioGroup>],['Starting Invoice No.',<TextField size="small" defaultValue={invoice.invoiceNo} sx={{width:150}}/>],['Ending Invoice No.',<TextField size="small" defaultValue={invoice.invoiceNo} sx={{width:150}}/>],['Print In',<RadioGroup value={printIn} onChange={e=>setPrintIn(e.target.value)}><FormControlLabel value="PKR" control={<Radio size="small"/>} label="PKR Currency" sx={{height:23,m:0,fontWeight:700}}/><FormControlLabel value="FOREIGN" control={<Radio size="small"/>} label="Foreign Currency" sx={{height:23,m:0,fontWeight:700}}/></RadioGroup>],['Print F/Currency Totals',option('foreignTotals')],['Print',<RadioGroup defaultValue="ORIGINAL">{['ORIGINAL','REVISED','DUPLICATE','OFFICE_COPY','ADDITIONAL','CORRECTED'].map(v=><FormControlLabel key={v} value={v} control={<Radio size="small"/>} label={v.replace('_',' ')} sx={{height:23,m:0,fontWeight:700}}/>)}</RadioGroup>],['Print MBL/HBL No.',option('mblHbl')],['Print Quotation No. on Invoice',option('quotation')],['Print Due Date',option('dueDate')],['Print Consignee',option('consignee')],['Print On',<RadioGroup value={paper} onChange={e=>setPaper(e.target.value)}><FormControlLabel value="LETTER" control={<Radio size="small"/>} label="Letter Pad" sx={{height:23,m:0,fontWeight:700}}/><FormControlLabel value="PLAIN" control={<Radio size="small"/>} label="Plain Paper" sx={{height:23,m:0,fontWeight:700}}/></RadioGroup>],['Print SPO Code/Name',option('spo')],['Print Party Code',option('party')],['Print Ex. Rate',option('rate')],['Print Received By',option('received')],['Print Signatorys',option('signatory')],['Print NTN No.',option('ntn')]];
  return <Box sx={{maxWidth:720}}><Typography component="div" sx={{display:'inline-block',px:1.5,py:.7,mb:.75,borderRadius:1,bgcolor:'#075a9d',color:'white',fontSize:20,fontWeight:700,boxShadow:2}}>LOCAL INVOICE ENTRY (SEA - IMPORT)</Typography><Box sx={{display:'flex',alignItems:'flex-start',gap:1.5}}><Paper variant="outlined" sx={{width:430,overflow:'hidden'}}><Box sx={{display:'grid',gridTemplateColumns:'200px 1fr','& > *':{minHeight:38,borderBottom:'1px solid #d7dee8'}}}>{rows.flatMap(([label,control],i)=>[<Box key={`${i}l`} sx={{p:.75,bgcolor:'#f1f5f9',fontWeight:700}}>{label}</Box>,<Box key={`${i}c`} sx={{p:.3}}>{control}</Box>])}</Box></Paper><Box sx={{display:'flex',gap:1,pt:.5}}><Button variant="contained" color="error" startIcon={<PictureAsPdfIcon/>} onClick={()=>window.print()}>PDF</Button><Button variant="outlined" color="success" startIcon={<TableViewIcon/>}>Excel</Button></Box></Box></Box>;
}
