import { confirmDelete } from '../../components/deleteConfirmation';
import { useMemo, useState } from 'react';
import Paper from '@mui/material/Paper';
import { IconButton, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField } from '@mui/material';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined'; import EditOutlinedIcon from '@mui/icons-material/EditOutlined'; import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'; import PrintOutlinedIcon from '@mui/icons-material/PrintOutlined';
import { SeaImportForeignAgentInvoice } from '../../domain/seaImportForeignAgentInvoice';
type Props={items:SeaImportForeignAgentInvoice[];onOpen:(i:SeaImportForeignAgentInvoice)=>void;onEdit:(i:SeaImportForeignAgentInvoice)=>void;onDelete:(i:SeaImportForeignAgentInvoice)=>void;onPrint:(i:SeaImportForeignAgentInvoice)=>void};
const headers=['No.','Date','Branch','Job No.','Code','Name','Mbl No.','Origin','Destination','Curr.','F/Amount','PKR','Final','Post','Void'];
export function SeaImportAgentGrid({items,onOpen,onEdit,onDelete,onPrint}:Props){const[f,setF]=useState<Record<number,string>>({});const[p,setP]=useState(0);const[n,setN]=useState(10);const values=(i:SeaImportForeignAgentInvoice)=>[i.documentNo,i.documentDate,i.branch,i.jobNo,i.fAgentCode,i.fAgentName,i.blNo,i.origin,i.destination,i.currencyCode,i.totalAmount,i.totalAmount*i.exchangeRate,i.status.final?'Y':'N',i.status.posted?'Y':'N',i.status.void?'Y':'N'].map(v=>String(v??''));const rows=useMemo(()=>items.filter(i=>values(i).every((v,k)=>v.toLowerCase().includes((f[k]??'').toLowerCase()))),[items,f]);return <TableContainer component={Paper} variant="outlined"><Table size="small" sx={{minWidth:1800}}><TableHead><TableRow><TableCell rowSpan={2}>Action</TableCell><TableCell colSpan={3} align="center">DOCUMENT</TableCell><TableCell rowSpan={2}>Job No.</TableCell><TableCell colSpan={2} align="center">F/AGENT</TableCell><TableCell rowSpan={2}>Mbl No.</TableCell><TableCell rowSpan={2}>Origin</TableCell><TableCell rowSpan={2}>Destination</TableCell><TableCell rowSpan={2}>Curr.</TableCell><TableCell colSpan={2} align="center">AMOUNT</TableCell><TableCell colSpan={3} align="center">STATUS</TableCell></TableRow><TableRow>{['No.','Date','Branch','Code','Name','F/Amount','PKR','Final','Post','Void'].map((x,k)=><TableCell key={`${x}${k}`}>{x}</TableCell>)}</TableRow><TableRow><TableCell/>{headers.map((x,k)=><TableCell key={`${x}${k}`}><TextField size="small" fullWidth type={x==='Date'?'date':'text'} placeholder={x} value={f[k]??''} onChange={e=>{setF(a=>({...a,[k]:e.target.value}));setP(0)}}/></TableCell>)}</TableRow></TableHead><TableBody>{rows.slice(p*n,p*n+n).map(i=><TableRow key={i.id} hover><TableCell sx={{whiteSpace:'nowrap',minWidth:135}}><IconButton size="small" onClick={()=>onOpen(i)}><VisibilityOutlinedIcon fontSize="small"/></IconButton><IconButton size="small" onClick={()=>onEdit(i)}><EditOutlinedIcon fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>confirmDelete(() => onDelete(i))}><DeleteOutlineIcon fontSize="small"/></IconButton><IconButton size="small" onClick={()=>onPrint(i)}><PrintOutlinedIcon fontSize="small"/></IconButton></TableCell>{values(i).map((v,k)=><TableCell key={k}>{v||'—'}</TableCell>)}</TableRow>)}</TableBody></Table><TablePagination component="div" count={rows.length} page={p} rowsPerPage={n} onPageChange={(_,x)=>setP(x)} onRowsPerPageChange={e=>{setN(+e.target.value);setP(0)}} rowsPerPageOptions={[5,10,25,50]}/></TableContainer>}
