import { useMemo, useState } from 'react';
import Paper from '@mui/material/Paper';
import { IconButton, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField } from '@mui/material';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import PrintOutlinedIcon from '@mui/icons-material/PrintOutlined';
import { AirImportLocalInvoice } from '../../domain/airImportLocalInvoice';

type Props = { invoices: AirImportLocalInvoice[]; onOpen: (invoice: AirImportLocalInvoice) => void; onEdit: (invoice: AirImportLocalInvoice) => void; onDelete: (invoice: AirImportLocalInvoice) => void; onPrint: (invoice: AirImportLocalInvoice) => void };
const columns = ['No.', 'Date', 'Branch', 'No.', 'Type', 'MAWB', 'No.', 'Weight', 'Code', 'Name', 'Origin', 'Destination', 'Curr.', 'Foreign', 'PKR', 'Final', 'Post', 'Void'];
export function AirImportLocalInvoiceGrid({ invoices, onOpen, onEdit, onDelete, onPrint }: Props) {
  const [filters, setFilters] = useState<Record<number, string>>({}); const [page, setPage] = useState(0); const [rowsPerPage, setRowsPerPage] = useState(10);
  const values = (i: AirImportLocalInvoice) => [i.invoiceNo, i.date, i.branch, i.jobNo, i.jobType, i.mawbNo, i.hawbNo, i.hawbChargeWeight, i.partyCode, i.partyName, i.origin, i.destination, i.currencies[0]?.currencyCode ?? '', i.invoiceTotal, i.invoiceTotalPkr, i.status.final ? 'Y' : 'N', i.status.posted ? 'Y' : 'N', i.status.void ? 'Y' : 'N'].map((v) => String(v ?? ''));
  const filtered = useMemo(() => invoices.filter((invoice) => values(invoice).every((value, index) => value.toLowerCase().includes((filters[index] ?? '').toLowerCase()))), [invoices, filters]); const rows = filtered.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage);
  return <TableContainer component={Paper} variant="outlined"><Table size="small" sx={{ minWidth: 2050 }}><TableHead><TableRow><TableCell rowSpan={2}>Action</TableCell><TableCell colSpan={3} align="center">INVOICE</TableCell><TableCell colSpan={2} align="center">JOB</TableCell><TableCell rowSpan={2}>MAWB</TableCell><TableCell colSpan={2} align="center">HAWB</TableCell><TableCell colSpan={2} align="center">PARTY</TableCell><TableCell rowSpan={2}>Origin</TableCell><TableCell rowSpan={2}>Destination</TableCell><TableCell rowSpan={2}>Curr.</TableCell><TableCell colSpan={2} align="center">AMOUNT</TableCell><TableCell colSpan={3} align="center">STATUS</TableCell></TableRow><TableRow>{['No.', 'Date', 'Branch', 'No.', 'Type', 'No.', 'Weight', 'Code', 'Name', 'Foreign', 'PKR', 'Final', 'Post', 'Void'].map((column, index) => <TableCell key={`${column}-${index}`}>{column}</TableCell>)}</TableRow><TableRow><TableCell />{columns.map((column, index) => <TableCell key={`${column}-${index}`}><TextField size="small" fullWidth type={column === 'Date' ? 'date' : 'text'} placeholder={column} value={filters[index] ?? ''} onChange={(event) => { setFilters((current) => ({ ...current, [index]: event.target.value })); setPage(0); }} /></TableCell>)}</TableRow></TableHead><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={19} align="center">No data available in table</TableCell></TableRow> : rows.map((invoice) => <TableRow key={invoice.id} hover><TableCell sx={{ whiteSpace: 'nowrap' }}><IconButton size="small" onClick={() => onOpen(invoice)}><VisibilityOutlinedIcon fontSize="small" /></IconButton><IconButton size="small" onClick={() => onEdit(invoice)}><EditOutlinedIcon fontSize="small" /></IconButton><IconButton size="small" color="error" onClick={() => onDelete(invoice)}><DeleteOutlineIcon fontSize="small" /></IconButton><IconButton size="small" onClick={() => onPrint(invoice)}><PrintOutlinedIcon fontSize="small" /></IconButton></TableCell>{values(invoice).map((value, index) => <TableCell key={`${invoice.id}-${index}`}>{value || '—'}</TableCell>)}</TableRow>)}</TableBody></Table><TablePagination component="div" count={filtered.length} page={page} rowsPerPage={rowsPerPage} onPageChange={(_, nextPage) => setPage(nextPage)} onRowsPerPageChange={(event) => { setRowsPerPage(Number(event.target.value)); setPage(0); }} rowsPerPageOptions={[5, 10, 25, 50]} /></TableContainer>;
}
