import { confirmDelete } from '../../components/deleteConfirmation';
import { useMemo, useState } from 'react';
import Paper from '@mui/material/Paper';
import { IconButton, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField } from '@mui/material';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import PrintOutlinedIcon from '@mui/icons-material/PrintOutlined';
import { AirImportJob } from '../../domain/airImportJob';

type Props = { jobs: AirImportJob[]; onOpen: (job: AirImportJob) => void; onEdit: (job: AirImportJob) => void; onDelete: (job: AirImportJob) => void; onPrint: (job: AirImportJob) => void };
const columns = ['No.', 'Date', 'Branch', 'MAWB No.', 'HAWB No.', 'Party/Agent Party Name/SPO Name', 'HS Code', 'Origin', 'Destination', 'No of Pkgs', 'Ch. Weight', 'Final', 'Void'];

export function AirImportJobGrid({ jobs, onOpen, onEdit, onDelete, onPrint }: Props) {
  const [filters, setFilters] = useState<Record<number, string>>({}); const [page, setPage] = useState(0); const [rowsPerPage, setRowsPerPage] = useState(10);
  const values = (job: AirImportJob) => [job.jobNo, job.jobDate, job.branch, job.mawbNo, job.hawbNo, job.partyName || job.spoCode, job.hsCode, job.origin, job.destination, job.hawbPcs || job.mawbPcs, job.hawbChargeWeight || job.mawbChargeWeight, job.status.final ? 'Y' : 'N', job.status.void ? 'Y' : 'N'].map((value) => String(value ?? ''));
  const filtered = useMemo(() => jobs.filter((job) => values(job).every((value, index) => value.toLowerCase().includes((filters[index] ?? '').toLowerCase()))), [jobs, filters]);
  const rows = filtered.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage);
  return <TableContainer component={Paper} variant="outlined"><Table size="small" sx={{ minWidth: 1800 }}><TableHead><TableRow><TableCell rowSpan={2}>Action</TableCell><TableCell colSpan={3} align="center">JOB</TableCell><TableCell rowSpan={2}>MAWB No.</TableCell><TableCell rowSpan={2}>HAWB No.</TableCell><TableCell rowSpan={2}>PARTY/AGENT PARTY NAME/SPO NAME</TableCell><TableCell rowSpan={2}>HS Code</TableCell><TableCell rowSpan={2}>Origin</TableCell><TableCell rowSpan={2}>Destination</TableCell><TableCell rowSpan={2}>No of Pkgs</TableCell><TableCell rowSpan={2}>Ch. Weight</TableCell><TableCell colSpan={2} align="center">STATUS</TableCell></TableRow><TableRow>{['No.', 'Date', 'Branch', 'Final', 'Void'].map((column) => <TableCell key={column}>{column}</TableCell>)}</TableRow><TableRow><TableCell />{columns.map((column, index) => <TableCell key={column}><TextField size="small" fullWidth type={column === 'Date' ? 'date' : 'text'} placeholder={column} value={filters[index] ?? ''} onChange={(event) => { setFilters((current) => ({ ...current, [index]: event.target.value })); setPage(0); }} /></TableCell>)}</TableRow></TableHead><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={14} align="center">No data available in table</TableCell></TableRow> : rows.map((job) => <TableRow key={job.id} hover><TableCell sx={{ whiteSpace: 'nowrap' }}><IconButton size="small" onClick={() => onOpen(job)}><VisibilityOutlinedIcon fontSize="small" /></IconButton><IconButton size="small" onClick={() => onEdit(job)}><EditOutlinedIcon fontSize="small" /></IconButton><IconButton size="small" color="error" onClick={() => confirmDelete(() => onDelete(job))}><DeleteOutlineIcon fontSize="small" /></IconButton><IconButton size="small" onClick={() => onPrint(job)}><PrintOutlinedIcon fontSize="small" /></IconButton></TableCell>{values(job).map((value, index) => <TableCell key={`${job.id}-${columns[index]}`}>{value || '—'}</TableCell>)}</TableRow>)}</TableBody></Table><TablePagination component="div" count={filtered.length} page={page} rowsPerPage={rowsPerPage} onPageChange={(_, nextPage) => setPage(nextPage)} onRowsPerPageChange={(event) => { setRowsPerPage(Number(event.target.value)); setPage(0); }} rowsPerPageOptions={[5, 10, 25, 50]} /></TableContainer>;
}
