import { useMemo, useState } from 'react';
import Paper from '@mui/material/Paper';
import { IconButton, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField } from '@mui/material';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import PrintOutlinedIcon from '@mui/icons-material/PrintOutlined';
import { SeaImportManifest } from '../../domain/seaImportManifest';
type Props = { manifests: SeaImportManifest[]; onOpen: (manifest: SeaImportManifest) => void; onEdit: (manifest: SeaImportManifest) => void; onDelete: (manifest: SeaImportManifest) => void; onPrint: (manifest: SeaImportManifest) => void };
const headers = ['Branch', 'No.', 'Date', 'HAWB No.', 'PCS', 'CBM', 'Gross Weight', 'Charge Weight', 'Destination', 'Origin'];
export function SeaImportManifestGrid({ manifests, onOpen, onEdit, onDelete, onPrint }: Props) { const [filters, setFilters] = useState<Record<number, string>>({}); const [page, setPage] = useState(0); const [rowsPerPage, setRowsPerPage] = useState(10); const values = (m: SeaImportManifest) => { const line = m.hblLines[0]; return [m.branch, line?.jobNo ?? m.consoleJobNo, m.jobDate, line?.hblNo ?? m.mblNo, m.pcs, m.cbm, m.grossWeight, m.netWeight, m.destination, m.portOfLoading].map((v) => String(v ?? '')); }; const filtered = useMemo(() => manifests.filter((m) => values(m).every((v, index) => v.toLowerCase().includes((filters[index] ?? '').toLowerCase()))), [manifests, filters]); const rows = filtered.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage); return <TableContainer component={Paper} variant="outlined"><Table size="small" sx={{ minWidth: 1450 }}><TableHead><TableRow><TableCell rowSpan={2}>Action</TableCell><TableCell colSpan={3} align="center">Job</TableCell><TableCell rowSpan={2}>HAWB No.</TableCell><TableCell colSpan={4} align="center">Total</TableCell><TableCell rowSpan={2}>Destination</TableCell><TableCell rowSpan={2}>Origin</TableCell></TableRow><TableRow>{['Branch', 'No.', 'Date', 'PCS', 'CBM', 'Gross Weight', 'Charge Weight'].map((h) => <TableCell key={h}>{h}</TableCell>)}</TableRow><TableRow><TableCell />{headers.map((h, index) => <TableCell key={h}><TextField size="small" fullWidth type={h === 'Date' ? 'date' : 'text'} placeholder={h} value={filters[index] ?? ''} onChange={(e) => { setFilters((current) => ({ ...current, [index]: e.target.value })); setPage(0); }} /></TableCell>)}</TableRow></TableHead><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={11} align="center">No data available in table</TableCell></TableRow> : rows.map((m) => <TableRow key={m.id} hover><TableCell sx={{ whiteSpace: 'nowrap' }}><IconButton size="small" onClick={() => onOpen(m)}><VisibilityOutlinedIcon fontSize="small" /></IconButton><IconButton size="small" onClick={() => onEdit(m)}><EditOutlinedIcon fontSize="small" /></IconButton><IconButton size="small" color="error" onClick={() => onDelete(m)}><DeleteOutlineIcon fontSize="small" /></IconButton><IconButton size="small" onClick={() => onPrint(m)}><PrintOutlinedIcon fontSize="small" /></IconButton></TableCell>{values(m).map((v, index) => <TableCell key={`${m.id}-${index}`}>{v || '—'}</TableCell>)}</TableRow>)}</TableBody></Table><TablePagination component="div" count={filtered.length} page={page} rowsPerPage={rowsPerPage} onPageChange={(_, next) => setPage(next)} onRowsPerPageChange={(e) => { setRowsPerPage(Number(e.target.value)); setPage(0); }} rowsPerPageOptions={[5, 10, 25, 50]} /></TableContainer>; }
